config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :products, only: [:index]
  resources :color_shades, only: [:index, :create] do
    resources :sub_products, only: [:index]
  end
  resources :sub_products, only: [:show]
  resources "order_products", only: [:index, :destroy, :update]
  resources "orders", only: [:index, :create, :update]
  resources "favourites", only: [:index, :create, :destroy]

  get "my_shades", to: "color_shades#image_upload", as: :my_shades
  # get "my_orders", to: "orders#my_orders", as: :my_orders
  post "order_products", to: "order_products#custom_create", as: :order_product_custom_create
  # get "my_cart", to: "orders#show", as: :my_cart

  get "payment", to: "order_products#payment", as: :payment
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/color_shade.rb
class ColorShade < ApplicationRecord
  has_many :users
  has_many :sub_products
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :sub_product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :sub_product
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :sub_product
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :sub_products, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/sub_product.rb
class SubProduct < ApplicationRecord
  belongs_to :product
  belongs_to :color_shade
  has_many :orderProducts
  has_many :orders, through: :orderProducts
  has_many :favourites
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :order_products
  has_one :color_shade
  has_one_attached :pic
  has_many :favourites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :show_items, :set_color_shades
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def show_items
    @order_products_items = OrderProduct.all.length
  end

  def set_color_shades
    @color_shades = ColorShade.all
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/color_shades_controller.rb
class ColorShadesController < ApplicationController
  def index
    @color_shades = ColorShade.all
  end

  def image_upload
    @color_shades = ColorShade.all
  end

  def create
    current_user.pic.attach(params[:this_user][:pic])
    redirect_to my_shades_path
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favourites = current_user.favourites
  end

  def show
    @favourite = Favourite.find(params[:id])
  end

  def create
    unless current_user.favourites.where(sub_product_id: params[:sub_product]).exists?
      @favourite = Favourite.create(
        {
          user_id: current_user.id,
          sub_product_id: params[:sub_product]
        }
      )
      @favourite.save!
    end
    redirect_to sub_product_path(params[:sub_product]), notice: 'Item added to Favourites'
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy
    redirect_to favourites_path, status: :see_other
  end

  private

  def favourites_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end
end

app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @cart = current_user.order_products
  end

  def show
    @order_product = OrderProduct.find(params[:id])
  end

  def custom_create
    op = current_user.order_products.where(sub_product_id: params[:subproduct])
    if op.exists?
      op = op.take
      op.update(
        {
          quantity: op.quantity + 1
        }
      )
    else
      @order_product = OrderProduct.create(
        {
          user_id: current_user.id,
          sub_product_id: params[:subproduct],
          user: current_user,
          quantity: 1
        }
      )
      @order_product.save!
    end
    redirect_to request.referrer, notice: 'Item added to cart'
  end

  def destroy
    @order_product = OrderProduct.find(params[:id])
    @order_product.destroy
    redirect_to order_products_path, status: :see_other
  end

  def update
    @order_product = OrderProduct.find(params[:id])
    @order_product.update(orderproducts_params)
    redirect_to order_products_path, status: 303
    # anchor means put at # in the url (anchor: "order-product-#{@order_product.id}")
  end

  def payment
    @cart = current_user.order_products
    @sub_total = (@cart.map { |item| item.sub_product.product.price * item.quantity }).sum
    @vat = 20
    @vat_amount = @sub_total * @vat / 100
    @total = @sub_total + @vat_amount
  end

  private

  def orderproducts_params
    params.require(:order_product).permit(:quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders.order(created_at: :desc)
  end

  def show
  end

  def create
    current_user.order_products.each do |item|
      @order = Order.create(
        {
          user_id: item.user_id,
          sub_product_id: item.sub_product_id,
          quantity: item.quantity,
          price: item.sub_product.product.price,
          status: "ORDERED"
        }
      )
      item.destroy if @order.save!
    end
    redirect_to orders_path, notice: 'Congratulations 🎉 Your order has been placed!'
  end

  def update
    @order = Order.find(params[:id])
    @order.update(
      status: "CANCELLED"
    )
    redirect_to orders_path, status: :see_other
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home
  def home
    @color_shades = ColorShade.all
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @color_shades = ColorShade.all
    if params[:query].present?
      sql_query = "brand_name ILIKE :query"
      @products = Product.where(sql_query, query: "%#{params[:query]}%")
    else
      @products = Product.all
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
  end

  private

  def review_params
    params.require(:review).permit[:content, :rating, :product_id]
  end
end

app/controllers/sub_products_controller.rb
class SubProductsController < ApplicationController
  def index
    @color_shades = ColorShade.all
    @sub_products = SubProduct.where(color_shade_id: params[:color_shade_id])
  end

  def show
    @color_shades = ColorShade.all
    @sub_product = SubProduct.find(params[:id])
    @product = @sub_product.product
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/color_shades/image_upload.html.erb
<h1 class="foundation-heading"> Select your shade </h1>

<div class="image-color-selector-container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-4">
      <div>
        <div id="color-selector"></div>
      </div>

      <% if current_user.pic.attached? %>
        <%= image_tag current_user.pic, alt: "user-image", class: "img-color" %>
      <% else %>
        <%= image_tag ("user.png"), class: "user-image-placeholder" %>
      <% end %>
    </div>
    <div class="col-md-4">
      <ul id="shade-pick">
        <% @color_shades.each do |shade| %>
          <%= link_to color_shade_sub_products_path(shade) do %>
            <li class="shade-block shade-tooltip" style="background: <%= shade.shade_hex %>;">
              <span class="tooltiptext"> <%= shade.shade_name %> </span>
            </li>
          <% end %>
        <% end %>
      </ul>
      <div>
        <%= simple_form_for :this_user, url: "color_shades", html: { class: "form-upload" } do |f| %>
        <%= f.input :pic, as: :file, direct_upload: true, input_html: { class: "d-none" }, label_html: { class: "upload-photo" }, label: "📷 Upload a photo" %>
        <%= f.submit "Upload", class: "btn btn-dark button-black" %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/color_shades/index.html.erb
<h2> Select your shade </h2>
<ul style="display: flex; flex-wrap: wrap; list-style-type: none;">
  <% @color_shades.each do |shade| %>
    <%= link_to color_shade_sub_products_path(shade) do %>
      <li style="margin: 5px; height: 40px; width: 40px; background: <%= shade.shade_hex %>;"> </li>
    <% end %>
  <% end %>
</ul>

app/views/favourites/index.html.erb
<h1 class="foundation-heading"> My Wishlists</h1>
<div class="products-container">
  <% @favourites.each do |item| %>
    <div class="products-card">
        <div class="image-price">
          <%= image_tag item.sub_product.img_main, class: "card-img-top", alt: "foundation image" %>
          <p class="price">$<%= item.sub_product.product.price %></p>
        </div>
      <div class="product-content">
        <h5 class="brand-name"> <%= item.sub_product.product.brand_name %> </h5>
        <p> <%= item.sub_product.product.name %> </p>
        <p> <%= item.sub_product.product.description.first(50) %> </p>
      </div>
        <div class="fav-delete-link-button">
          <%= link_to image_tag("delete.png"), favourite_path(item), data: { turbo_method: :delete } %>
        </div>

        <div class="justify-content-around">
          <p class="my-button link-button"><%= link_to "Add to cart", order_product_custom_create_path(subproduct: item.sub_product_id), data: { turbo_method: :POST } %></p>
        </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shades: your personal makeup assistant</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag "favicon.png" %>

  </head>

  <body data-controller="cart navbar" data-cart-product-value="<%= current_user ? current_user.orders.to_json : nil %>">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
      <%= yield %>
    <%= render "shared/footer" %>
  </body>
  <script>

  </script>
</html>

app/views/order_products/index.html.erb
<h1 class="foundation-heading"> Shopping Bag</h1>
<div class="products-container-cart">
  <% @cart.each do |item| %>
    <div id="order-product-<%= item.id %>" class="products-card-card">
      <%= image_tag item.sub_product.img_main, class: "card-img-top", alt: "foundation image" %>
      <div class="product-content">
        <div class="d-flex">
          <h5 class="brand-name"> <%= item.sub_product.product.brand_name %> </h5>
        </div>
        <p> <%= item.sub_product.product.name %> </p>
        <p class="d-flex"> Shade: <%= item.sub_product.color_shade.shade_name %> </p>
        <div class="d-flex align-items-center">
          <%= simple_form_for item, html: { 'data-turbolinks-scroll': false } do |f| %>
            <%= f.hidden_field :quantity, value: item.quantity - 1 %>
            <%= f.submit "-", class: "quantity-btn" %>
          <% end %>
          <span class="quantity-btn"><%= item.quantity %></span>

          <%= simple_form_for item, html: { 'data-turbolinks-scroll': false } do |f| %>
            <%= f.hidden_field :quantity, value: item.quantity + 1 %>
            <%= f.submit "+", class: "quantity-btn" %>
          <% end %>

          <div class="delete-link-button">
            <%= link_to  image_tag("delete.png"), order_product_path(item), data: { turbo_method: :delete } %>
          </div>
        </div>
      </div>
      <div class="cart-price">
        <span >$<%= item.sub_product.product.price * item.quantity %></span>
      </div>
    </div>
  <% end %>
  <div class="cart-button">
    <% if @cart.exists? %>
      <div class="my-button link-button w-100 mt-4">
        <%= link_to "Make Payment", payment_path %>
      </div>
    <% else %>
      <div class="empty-cart">
        <%= image_tag "empty_cart.png" %>
      </div>
      <div class="my-button link-button w-100 mt-4">
        <%= link_to "Go Shopping", products_path, class: "w-100" %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/index.html.erb
<h1 class="foundation-heading"> Orders</h1>
<div class="products-container-cart">
  <% if @orders.exists? %>
    <% @orders.each do |item| %>
      <div class="products-card-card">
          <div class="image-price">
            <%= image_tag item.sub_product.img_main, class: "card-img-top", alt: "foundation image" %>
            <p class="price">$<%= item.price * item.quantity %></p>
          </div>
        <div class="card-product-infos">
          <h5 class="brand-name"> <%= item.sub_product.product.brand_name %> </h5>
          <p> <%= item.sub_product.product.name %> </p>
          <p> <%= item.sub_product.product.description.first(50) %> </p>
          <p> Quantity: <%= item.quantity %></p>
            <% if item.status == "ORDERED" %>
              <div class="order-cancel-button">
              <%= link_to "Cancel", order_path(item), data: { turbo_method: :patch } %>
            </div>
            <% else %>
              <div></div>
            <% end %>

        </div>
        <p>Status: <%= item.status %></p>
        <% if item.status == "ORDERED" %>
          <p> Expected delivery: <%= (item.created_at + 7.days).to_date %></p>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="products-card-card">
      <%= image_tag "empty_cart.png" %>
    </div>
    <div class="my-button link-button w-100 mt-4">
      <%= link_to "Go Shopping", products_path, class: "w-100" %>
    </div>
  <% end %>
</div>

app/views/pages/_banner.html.erb
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel" data-navbar-target="banner" data-bs-interval="3000">
  <div class="carousel-inner">
    <div class="carousel-item banner active" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_url("home-background.jpg") %>);">
      <div class="banner-content">
        <h1 class=banner-heading>SHADES</h1>
        <p>“Enhance your natural beauty”</p>
      </div>
      <%= link_to my_shades_path do %>
        <div class="banner-cta">
          <div class="arrow">
              <span></span>
              <span></span>
              <span></span>
          </div>
          <h2>Start your journey, find the perfect shade for you.</h2>
        </div>
      <% end %>
    </div>
    <div class="carousel-item banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_url("home-background-2.jpg") %>);">
      <div class="banner-content">
        <h1 class=banner-heading>SHADES</h1>
        <p>“Enhance your natural beauty”</p>
      </div>
      <%= link_to my_shades_path do %>
        <div class="banner-cta">
            <div class="arrow">
              <span></span>
              <span></span>
              <span></span>
            </div>
          <h2>Start your journey, find the perfect shade for you.</h2>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render "banner" %>

  <h2 class="home-heading"> Our New Arrivals </h2>
  <div class="products-container-home">
  <% @products.first(3).each do |product| %>
      <div class="products-card">
      <div>
        <div class="image-price">
          <%= link_to sub_product_path(product.sub_products[0]) do %>
          <%= image_tag product.sub_products[0].img_main, alt: "foundation images" %>
          <% end %>
          </div>
          <div class='d-flex w-100 justify-content-center'> <div class="price-product"><p>$<%= product.price %></p></div></div>
        </div>
        <div class="product-content">
          <h5 class="brand-name"> <%= link_to product.brand_name, sub_product_path(product.sub_products[0]) %> </h5>

        </div>
        <div class="d-flex justify-content-around">
          <p class="my-button"> <%= link_to "Choose your shade", sub_product_path(product.sub_products[0]) %></p>
        </div>
      </div>
  <% end %>
</div>

  <div class="discover-more">
    <%= link_to "Discover More", products_path(@product) %>
  </div>
<h1 class="home-heading">How It Works</h1>
<div class="home-cards-container">
  <div class="home-card">
    <div class="home-card-header">
      <%= image_tag "facemakeup.png" %>
      <h3>Uploading Your Picture</h3> </div> <p>Click on the "Start" button on our homepage. You will be taken to a page where you can upload a clear picture of your face. The picture should be taken in good lighting and in focus so that you can choose a shade that matches your skin tone.</p>
  </div>
  <div class="home-card">
    <div class="home-card-header">
      <%= image_tag "blush.png" %>
      <h3>Choosing Your Shade</h3>
    </div>
    <p>Once you have uploaded your picture, you will be taken to our product page where you can see a range of makeup shades and foundations that match your skin tone. You can compare these shades to your uploaded picture to see which one looks the best on you.</p>
  </div>
  <div class="home-card">
    <div class="home-card-header">
      <%= image_tag "cart.png" %>
      <h3>Add to Cart</h3>
    </div>
    <p>Once you have found a shade that matches your skin tone, you can add the product to your cart or wishlist. If you're ready to buy, simply add the product to your cart and proceed to checkout</p>
  </div>
  <div class="home-card">
    <div class="home-card-header">
      <%= image_tag "package.png" %>
      <h3>Purchasing and Delivery</h3>
    </div>
    <p>When you're ready to purchase your products, simply click on the checkout button in your cart. You can pay securely using our payment gateway and your products will be shipped to your doorstep.</p>
  </div>
</div>

<div class="partners">
<h1 class="home-heading">Our Partners</h1>
<div class="partners-images">
<%= image_tag "it-cosmetics-logo.png" %>
<%= image_tag "make-up-forever-logo.jpg" %>
<%= image_tag "kvd-beauty-logo.jpg" %>
</div>
</div>

app/views/products/index.html.erb
<div class="products-banner">
<h1 class="foundation-heading">Foundations</h1>
</div>
<div class="products-container">
  <% @products.each do |product| %>
      <div class="products-card">
        <div>
          <div class="image-price">
            <%= link_to sub_product_path(product.sub_products[0]) do %>
            <%= image_tag product.sub_products[0].img_main, alt: "foundation images" %>
            <% end %>
          </div>
          <div class='d-flex w-100 justify-content-center'> <div class="price-product"><p>$<%= product.price %></p></div></div>
        </div>
        <div class="product-content">
          <h5 class="brand-name"> <%= link_to product.brand_name, sub_product_path(product.sub_products[0]) %> </h5>
          <i data-star=<%= product.rating %>> </i>
        </div>
        <div class="d-flex justify-content-around">
          <p class="my-button"> <%= link_to "Choose your shade", sub_product_path(product.sub_products[0]) %></p>
        </div>
      </div>
  <% end %>
</div>

app/views/shared/_color_dropdown.html.erb
<div class="dropdown" style="margin-top: 5%; margin-left: 15%;">
  <button class="btn btn-outline-dark dropdown-toggle choose-shade" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Choose your Shade
  </button>
  <div class="dropdown-menu" style="background-color: rgba(255,255,255,.75)" id="scroll-box" aria-labelledby="dropdownMenuButton">
    <% unless @color_shades.nil? %>
      <% @color_shades.each do |shade| %>
        <%= link_to color_shade_sub_products_path(shade), class: "dropdown-item color-dropdown" do %>
          <div class="nav-bar-color-picker" style="background: <%= shade.shade_hex %>;"></div>
          <div class="nav-bar-text"><%= shade.shade_name %></div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div>
<div class="footer-info">
  <div class="about">
    <a href="#"><p>About US</p></a>
    <a href="#"><p>Career</p></a>
    <a href="#"><p>FQS</p></a>
  </div>
  <div class="support">
    <a href="#"><p>Support</p></a>
    <a href="#"><p>Contact</p></a>
  </div>
  <div class="address">
    <p>Some straße </p>
    <p>Berlin 12345</p>
    <p>Germany</p>
  </div>
</div>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>
    © 2023 Shades Inc.    |    Terms & Conditions    |    Privacy policy
    </p>
  </div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-navbar-target="navbar" data-action="scroll@window->navbar#scrollAxis">
  <div class="container-fluid">
    <div class="d-flex">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.png", class: "img-logo" %>
      <% end %>
      <%= render "shared/color_dropdown" %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse me-3" id="navbarSupportedContent" style="font-weight: 600;">
    <% if user_signed_in? %>
      <ul class="navbar-nav me-auto gap-3">
        <li>
          <%= form_with url: products_path, method: :get, class: "d-flex" do %>
            <%= image_submit_tag("suche.png", class: "search-img") %>
            <%= text_field_tag :query,
                               params[:query],
                               class: "form-control",
                               placeholder: "" %>
          <% end %>
        </li>
      </ul>
          <li class="nav-item dropdown gap-3">
            <div class="shoppingcard_image_container">
              <% cart_items_count = current_user.order_products.sum(:quantity) %>
              <% if cart_items_count > 0 %>
                <div class="shoppingCardCirle" data-cart-target="shoppingCartCircle" style="display: block">
                  <h6> <%= cart_items_count %> </h6>
                </div>
              <% end %>
              <%= link_to order_products_path do %>
              <%= image_tag "shopping-cart.png", class: "nav-cart" %>
              <% end %>
            </div>
            <% if current_user.pic.attached? %>
              <%= cl_image_tag current_user.pic.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag ("user.png"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" id="drop-down-avatar" aria-labelledby="navbarDropdown">
              <%= link_to "All Foundations", products_path, class: "dropdown-item" %>
              <%= link_to "Favourites", favourites_path, class: "dropdown-item" %>
              <%= link_to "My Orders", orders_path, class: "dropdown-item" %>
              <%= link_to "Pick your shade", my_shades_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <%= link_to "Sign UP", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </div>
  </div>
</div>

app/views/sub_products/index.html.erb
<h1 class="foundation-heading"> Foundations for Your Skin Tone</h1>
<div class="products-container">
  <% @sub_products.shuffle(random: Random.new(42)).each do |sub_product| %>
      <div class="products-card">
          <div class="image-price">
          <%= link_to sub_product_path(sub_product) do %>
            <%= image_tag sub_product.img_main, class: "card-img-top", alt: "foundation image" %>
            <% end %>
          </div>
           <div class='d-flex w-100 justify-content-center'> <div class="price-product"><p>$<%= sub_product.product.price %></p></div></div>

        <div class="product-content product-content-style">
          <h5 class="brand-name"> <%= sub_product.product.brand_name %> </h5>
          <p> <%= sub_product.product.name %> </p>
          <p> <%= sub_product.product.description.first(50) %> </p>
        </div>

       <div class="products-button">
          <p class="my-button button-color"><%= link_to "Add to Cart", order_product_custom_create_path(subproduct: sub_product), data: { turbo_method: :POST }, 'data-turbolinks-scroll': false %></p>
        </div>
    </div>
<% end %>
</div>

app/views/sub_products/show.html.erb
<h2 class="product-heading foundation-heading"><%= @product.brand_name %></h2>
<div class="product-card-container">
  <div class="card-product">
    <div class="card-product-details">
      <div class="show-product-image">
        <%= image_tag @sub_product.img_main, class: "card-img-top", alt: "foundation image" %>
      </div>
      <div class="product-info">
        <div class="show-product-card">
          <% if !current_user.favourites.where(sub_product_id: @sub_product).exists? %>
            <div class="heart-icon">
              <%= link_to image_tag("heart.png"), favourites_path(sub_product: @sub_product), data: { turbo_method: :POST }, 'data-turbolinks-scroll': false %>
            </div>
          <% else %>
            <div class="heart-icon">
              <%= link_to image_tag("like.png") %>
            </div>
          <% end %>
          <div class="card-product-infos">
            <div>
              <h4> <%= @product.name %> </h4>
              <p>Shade : <%= @sub_product.name %> </p>
              <p> <%= @product.description %> </p>
              <i data-star=<%= @product.rating %>></i>
            </div>
          </div>
        </div>
        <div class="product-price">
          <div class="products-button">
            <p class="my-button link-button">
              <%= link_to "Add to Cart", order_product_custom_create_path(subproduct: @sub_product), data: { turbo_method: :POST }, 'data-turbolinks-scroll': false %>
            </p>
          </div>
          <div class="show-price">
            <p class="show-price-tag">$<%= @product.price %></p>
          </div>
        </div>
      </div>
    </div>

    <ul class="color-shades">
      <% @product.sub_products.each do |sub| %>
        <%= link_to sub_product_path(sub) do %>
          <li class="shade-tooltip", style="background-color: <%= sub.shade_hex %>;">
            <span class="tooltiptext"> <%= sub.name[0..3] %> </span>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>